PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(3,'2020_06_24_164230_create_categorias_table',1);
INSERT INTO migrations VALUES(4,'2020_06_24_164310_create_noticias_table',1);
INSERT INTO migrations VALUES(5,'2020_06_24_164344_create_avaliacaos_table',1);
INSERT INTO migrations VALUES(6,'2020_06_24_164434_create_comentarios_table',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime null, "password" varchar not null, "remember_token" varchar null, "nivel" integer not null default '2', "created_at" datetime null, "updated_at" datetime null);
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer not null primary key autoincrement, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime default CURRENT_TIMESTAMP not null);
CREATE TABLE IF NOT EXISTS "categorias" ("id" integer not null primary key autoincrement, "usuario_id" integer not null, "nome" varchar not null, "created_at" datetime null, "updated_at" datetime null, foreign key("usuario_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "noticias" ("id" integer not null primary key autoincrement, "usuario_id" integer not null, "categoria_id" integer not null, "titulo" varchar not null, "resumo" varchar not null, "conteudo" varchar not null, "created_at" datetime null, "updated_at" datetime null, foreign key("usuario_id") references "users"("id"), foreign key("categoria_id") references "categorias"("id"));
CREATE TABLE IF NOT EXISTS "avaliacaos" ("id" integer not null primary key autoincrement, "usuario_id" integer not null, "noticia_id" integer not null, "relevante" tinyint(1) not null, "created_at" datetime null, "updated_at" datetime null, foreign key("usuario_id") references "users"("id"), foreign key("noticia_id") references "noticias"("id"));
CREATE TABLE IF NOT EXISTS "comentarios" ("id" integer not null primary key autoincrement, "usuario_id" integer not null, "noticia_id" integer not null, "comentario" varchar not null, "created_at" datetime null, "updated_at" datetime null, foreign key("usuario_id") references "users"("id"), foreign key("noticia_id") references "noticias"("id"));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',6);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE UNIQUE INDEX "categorias_nome_unique" on "categorias" ("nome");
COMMIT;
